# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alanyeh's Blog
tagline:          '改變。此刻'
description:      '小強的技術分享部落格：）'
url:              https://github.com/alanyeh20001
baseurl:          /

author:
  name:           'Alan Yeh'
  email:          alanyeh200001@gmail.com

paginate:         5

github:           https://github.com/alanyeh20001
flickr:           https://www.flickr.com/photos/114787703@N02/
pixnet:           http://alanyeh20001.pixnet.net/blog

# Plugins
plugins:          [jekyll-paginate]
